### ISSUE TITLE
Hashing algorithm

### ISSUE THREAD

**Issue by zvr** [swhid/specification#16]
In many (all?) cases of identifiers, there is mention of a hashing algorithm.

It's usually described as "SHA-1", but there are also references to what `git` uses.

Since `git` has moved (years ago) to use the "_collision detecting SHA-1_" variant (as evidenced [here](https://github.com/git/git/blob/master/sha1dc_git.h)), do we have to be more precise?

We would need an absolute reference for the standard, anyway -- we now have [RFC-3174](https://github.com/swhid/specification/blob/642501a657a2f2f23f477c1280ffb7b83f47584e/Chapters/2.Normative_references.md?plain=1#L13-L16).

**Comment by rdicosmo** [comment]
Hi Alexios, very good point, we were discussing this just yesterday:-)

May you open an issue about this?

One aspect is deciding what must be in the standard, the other is pointing
at its precise specification.

Roberto

**Comment by zvr** [comment]
> May you open an issue about this?

Ehhmmm... yes, this is this issue. :wink:

**Comment by zacchiro** [comment]
OK, I've pushed a first proposal as PR #24. Happy to elaborate/discuss more after you've considered the proposal.
