### ISSUE TITLE
Names of filesystem objects

### ISSUE THREAD

**Issue by zvr** [swhid/specification#18]
OK, this is complicated... Apologies for the length.

In some of the identifier types (definitely `dir`) the _name_ of a file is used, e.g. in the calculation of the hash as well as in sorting the entries. There is currently no information about encoding, normalization, or collation. Collation algorithms are ultimately about sorting, normalization algorithms are ultimately about equality, and encoding methods are about representation.

How should entries like `S͉̙ͣofw̦̯ͥta͊͛́r̝ͤe_Heři̢͛t̓agë́.txt` or `S͉̙ͣofw̦̯ͥta͊͛́r̝ͤe_Heři̢͛t̓agë́.txt` be represented and sorted? (GitHub UI font is not useful for this example; feel free to copy-paste them elsewhere).

Let's start with a simpler example: a file about a fiancée, named `fiancée`.

**Issue 1 - Encoding**

How is this name represented? Unfortunately, it depends on the filesystem. Each filesystem uses an _encoding_ for representing characters. In theory, not even ASCII is safe, since there might be a system that uses ---I don't know--- EBCDIC. But when leaving the  7-bit ASCII, chances are greater that not everything would be UTF-8 (there are _many_ FAT volumes in cp1252).

_Question:_ Do we want to specify that everything is UTF-8?

**Issue 2 - Normalization**

Let's say we ignore issue 1 and deal only with the case of Unicode and UTF-8 encoding. We are not done yet! Unfortunately, UTF-8 does not have a unique way of encoding characters.

For demonstration purposes, feel free to run the following script (preferably in an empty directory, as it will overwrite files):
```Python
#!/usr/bin/env python3

# both of these are correct Unicode
b1 = b'fianc\xc3\xa9e'
b2 = b'fiance\xcc\x81e'
# the first uses a single code point, U+00E9, or LATIN SMALL LETTER E WITH ACUTE
# the second uses two code points: U+0065 (LATIN SMALL LETTER E) and U+0301 (COMBINING ACUTE ACCENT)

print(b1, b2, b1 == b2)

s1 = b1.decode("utf-8")
s2 = b2.decode("utf-8")
print(s1, s2, s1 == s2)

import sys
print('FYI filesystemencoding is', sys.getfilesystemencoding())

import os
os.mkdir('a')
os.mkdir('b')

for fname in (s1, s2, 'a/'+s1, 'b/'+s2):
    with open(fname, 'w') as f:
        f.write('hello' + '\n')

# now run: "swh identify *"
```

After running it on my (Linux) system (`"FYI filesystemencoding is utf-8"`), I got:
```
$ swh identify * 
swh:1:dir:2ed0df200324e6791ba765656d3a01e56c162a05      a
swh:1:dir:ff860d0c9e18f9a0c1eb88bf85de1b3e4ab9e774      b
swh:1:cnt:ce013625030ba8dba906f756967f9e9ca394464a      fiancée
swh:1:cnt:ce013625030ba8dba906f756967f9e9ca394464a      fiancée
```

So, besides the fun fact that in the current directory I have two different files with the "same" name(!), the two directories (`a` and `b`) have different SWHID.

_Question:_ Is this something we want, or do we want to normalize all representations to a unique one?

**Issue 3 - Collation**

Once you have such filesystem entries, how do you sort them? Does `fiancée` come before or after `fiancd`, `fiance`, `fiancf`?

**Summarizing:**

This is a very difficult problem, with no easy solution. We won't solve it for SWHID. But we have to document exactly what our assumptions are and understand what the consequences are. For example, are we OK with the same content producing different SWHIDs depending on where it is stored?

**References**

* https://docs.python.org/3/howto/unicode.html
* https://dwheeler.com/essays/fixing-unix-linux-filenames.html

**Comment by zvr** [comment]
To be fair, I've read the current spec and some things are explicitly mentioned (e.g. sorting of entries).

But we have to understand the problem and probably document our decisions about it.

**Comment by rdicosmo** [comment]
Hi Alexios,
    SWHIDs for directories are computed exactly the same way git does: 'filenames' are taken precisely as the 'byte sequence' stored in the filesystem, with no encoding whatsoever. The fact that two different byte sequences may appear the same when rendered on the screen may seem surprising, but does not matter.

@olasd and @zapashcanon : may you chime in?

**Comment by zvr** [comment]
Yes, @rdicosmo, I know the current state.

So we are OK with the same content producing different SWHIDs depending on where it is stored (filesystem encoding). Because storing the same files in a Linux/UTF-8 filesystem and a FAT/CP1251 one will produce different hashes.

**Comment by rdicosmo** [comment]
Closing this issue, as it is now resolved in the specification.
