### ISSUE TITLE
Q: one standard or two parts?

### ISSUE THREAD

**Issue by zvr** [swhid/specification#2]
Should the specification be a single or a two-parted standard?

By two parts, I mean that the _qualified SWHIDs_ are in a separate part, a `-2` standard.

For an example of what I'm talking about, look up ISO 8601:
- ISO 8601-1 defines the usual time and date formatting like `YYYY-MM-DD`; and
- ISO 8601-2 defines more extensions to this format, like uncertain or approximate dates, time intervals, etc.

Advantages of having a single part:
- everything in a single place

Advantages of having two parts:
- smaller specification, easier to understand
- probably helpful for usage and implementation, since it can (at a first stage) only support core identifiers

@rdicosmo @jfabramatic @zacchiro comments?

**Comment by rdicosmo** [comment]
Now we have a full specification done, including the qualifiers, that are a relatively small part of the whole, so a single specification seems the easiest way forward.

Any thoughts @zvr @zacchiro @jfabramatic ?

**Comment by zvr** [comment]
With the progress made in both parts, the argument about splitting the qualifiers into a separate part to not slow us down have been rendered irrelevant.

The only other argument would be whether we think that the qualifiers part will be evolving more and in a different pace than the core part. As far as I understand, there are no such plans (at least in the near future).

Therefore, I see no issue with having everything in a single piece.

**Comment by zacchiro** [comment]
> Therefore, I see no issue with having everything in a single piece.

I concur.

**Comment by rdicosmo** [comment]
Thanks for this feedback. Closing the issue.
