### ISSUE TITLE
The website entry page is not very helpful

### ISSUE THREAD

**Issue by lunar-debian** [swhid/specification#27]
Aiming a browser at https://www.swhid.org/governance/ currently leads to:

![image](https://github.com/swhid/specification/assets/24840614/f75c2538-e03f-4efd-9bca-195848bd31f8)

One can access important content after clicking “Governance” in the menu, which is the 6th option.

I guess either some kind of landing page or a reordering of the section would be worthwhile.

**Comment by rdicosmo** [comment]
Thanks for the feedback, this should go on https://github.com/swhid/swhid.github.io though, so closing it here. Feel free to make suggestions directly on https://github.com/swhid/swhid.github.io
