### ISSUE TITLE
Multiple same qualifiers of same type?

### ISSUE THREAD

**Issue by zvr** [swhid/specification#37]
The specification does not currently say anything about restricting qualifiers to single appearance.

For example, can a single SWHID have two `origin` qualifiers?

Do we need some wording that each one appears at maximum once? Or some of them, and other may appear multiple times?

**Comment by zacchiro** [comment]
Nice catch, thanks

Conceptually: we have always considered each qualifier to be unique, and not to be repeated.

In terms of formal specification, I _think_ that at some point we were sort-of-convinced that the SWHID URI-based syntax  was implicitly excluding parameter repetition.
But I'm no longer sure about that (and I haven't double checked).

And in any event I think it would be much better to state explicitly that qualifiers must not be repeated.

**Comment by rdicosmo** [comment]
Indeed, very good point! The current grammar allows repeated qualifiers, see:
https://github.com/swhid/specification/blob/8b7545562afbd0bfa049df659eb43f635e092ed4/Chapters/4.Syntax.md?plain=1#L27-L31

https://github.com/swhid/specification/pull/38 clarifies that each qualifier can occur at most once.

**Comment by rdicosmo** [comment]
This is now addressed in https://github.com/swhid/specification/pull/38
