### ISSUE TITLE
gpgsig in git can also be SSH signature instead of OpenGPG

### ISSUE THREAD

**Issue by castedo** [swhid/specification#48]
https://github.com/swhid/specification/blob/5c0717c338dc707a6f0744536b574684fd362898/Chapters/5.Core_identifiers.md?plain=1#L94

This line reads `or "gpgsig" (where the value is interpreted as an OpenPGP signature of the metadata of the revision).` However, the `gpgsig` is a bit of a misnomer now in that the signature can be SSH or x509 signatures too. See https://git-scm.com/docs/gitformat-signature

Perhaps better to just say a "cryptographic signature" rather than "OpenPGP signature".

**Comment by zacchiro** [comment]
PR welcome!

**Comment by castedo** [comment]
OK, sounds good. I will do a PR.

@zacchiro I am torn between

a tiny teeny change: `an OpenPGP signature of` -> `a cryptographic signature of`

VS

a bigger change: `an OpenPGP signature of` -> `an ASCII armor encoded cryptographic signature of`

Any thoughts?

I am inclined to go for the bigger one.

**Comment by zacchiro** [comment]
It's an example, so I don't think it matters much which one. But for what is worth I like the first one more, because it's easier to read/understand for the intended public.

**Comment by rdicosmo** [comment]
Merged #49
